### ISSUE TITLE
Error: entry already exists 

### ISSUE THREAD

**Issue by vikanren** [karnotxyz/avail-campaign-listing#1571]
My pr isnt merged but it says "entry already exists or invalid" when I commit my json file. How can I fix it please? I am sure its not invalid. My pr is still öpen, help me please.

**Comment by Sazy67** [comment]
sanırım   yanlış yerden bilgi istiyorsun..

**Comment by vikanren** [comment]
> sanırım yanlış yerden bilgi istiyorsun..

Nerden bilgi isteyebilirim, burda sorun var diye buraya yazdım. Yardımcı olacaksan ol olmayacaksan boş konuşma.

**Comment by DADIDUNG** [comment]
> My pr isnt merged but it says "entry already exists or invalid" when I commit my json file. How can I fix it please? I am sure its not invalid. My pr is still öpen, help me please.

Delete Fork && Refork && download file json from fork && Edit json to your infor App && Upload json to your fork repositories && create PR

**Comment by vikanren** [comment]
Do not to upload your .json in the app-chains folder on your fork.
