### ISSUE TITLE
Forgot to add /metrics in the end of metric_endpoint

### ISSUE THREAD

**Issue by aliabdy** [karnotxyz/avail-campaign-listing#5419]
Hi
I create a PR for madara node and it's merged successfully but I made a mistake and forgot to add "/metrics" in the end of metric_endpoint in JSON file.is this an issue or it doesn't matter?
this is my json config:
{
  "name": "smartcat",
  "logo": "https://i.ibb.co/WH5btBS/smartcat-logo.png",
  "rpc_url": "http://65.109.181.53:9944",
  "explorer_url": "http://65.109.181.53:4000",
  "metrics_endpoint": "http://65.109.181.53:9615",
  "id": "25949488-58ec-4594-b969-345958d8afad"
}

**Comment by ismaonezain** [comment]
u should upload the .json not this. u not communicating with human sir

**Comment by aliabdy** [comment]
> u should upload the .json not this. u not communicating with human sir

I upload .json file and make PR correctly but in metics_endpoint i forgot to add "/metrics" at the end of url

**Comment by botxx15** [comment]
Just open the file and add the /metrics and update your PR

**Comment by aliabdy** [comment]
> Just open the file and add the /metrics and update your PR

my PR is merged. I can not update it

**Comment by botxx15** [comment]
I think you can edit and update the repository that you already forked and just create new PR
