### ISSUE TITLE
Validate Entry Failing

### ISSUE THREAD

**Issue by botxx15** [karnotxyz/avail-campaign-listing#6033]
When I try to create pull request for my app chain the validate entry is always failing and I got this message on the logs. How to fix this?

![CleanShot 2024-02-10 at 02 54 35@2x](https://github.com/karnotxyz/avail-campaign-listing/assets/77204008/4c76d04a-0bb2-4ca1-b581-a1fa5947eb9d)

**Comment by Haleh92** [comment]
Same here!

**Comment by chiefbiiko** [comment]
Same

**Comment by Haleh92** [comment]
Update: They updated the repo and it's fixed now! [commit 4b00b52 - fix broken validate](https://github.com/karnotxyz/avail-campaign-listing/commit/4b00b52d56057d44f1b1114ea10915ec08fb604e)
